#!/usr/bin/with-contenv bash

echo "**** Starting Traefik ****"

if docker ps --format '{{ .Names }}' | grep -q traefik; then
    echo "Traefik is already running"
    exit 0
fi

if !(docker network ls | grep -q traefik); then
    docker network create traefik
fi

TRAEFIK_PORT=${TRAEFIK_PORT:-80}
TRAEFIK_PORT_SSL=${TRAEFIK_PORT_SSL:-443}
TRAEFIK_DASHBOARD_URL=${TRAEFIK_DASHBOARD_URL:-"traefik.localhost"}
TRAEFIK_DASHBOARD_AUTH=${TRAEFIK_DASHBOARD_AUTH:-""}
TRAEFIK_CONFIG_FILE=${TRAEFIK_CONFIG_FILE:-""}

echo "Starting Traefik on port ${TRAEFIK_PORT}"
echo "Use URL ${TRAFIK_DASHBOARD_URL} to access"

LABELS="\
    -l traefik.enable=true \
    -l traefik.http.routers.dashboard.rule=Host(\`${TRAEFIK_DASHBOARD_URL}\`) \
    -l traefik.http.routers.dashboard.service=api@internal \
"

if [ ! -z ${TRAEFIK_DASHBOARD_AUTH+x} ]; then
    echo "Dashboard authentification enabled"

    LABELS="${LABELS}\
        -l traefik.http.routers.dashboard.middlewares=dashboardauth \
        -l traefik.http.middlewares.dashboardauth.basicauth.users=${TRAEFIK_DASHBOARD_AUTH} \
    "
fi

CONFIG_FILE=""
if [ ! -z ${TRAEFIK_CONFIG_FILE} ]; then
    CONFIG_FILE = "-v ${TRAEFIK_CONFIG_FILE}:/etc/traefik/traefik.yml"
fi

docker run \
    --rm \
    -d \
    --name traefik \
    --privileged \
    -p ${TRAEFIK_PORT}:${TRAEFIK_PORT} \
    -p ${TRAEFIK_PORT_SSL}:${TRAEFIK_PORT_SSL} \
    --network traefik \
    -v /var/run/docker.sock:/var/run/docker.sock \
    ${CONFIG_FILE} \
    ${LABELS} \
    traefik:latest \
    --providers.docker \
    --providers.docker.exposedbydefault=false \
    --providers.docker.network=traefik \
    --api.dashboard=true \
    --entrypoints.web.address=":${TRAEFIK_PORT}" \
    --entrypoints.websecure.address=":${TRAEFIK_PORT_SSL}"