#!/usr/bin/with-contenv bash

echo "**** Starting Traefik ****"

if docker ps --format '{{ .Names }}' | grep -q traefik; then
    echo "Traefik is already running"
    exit 0
fi

if !(docker network ls | grep -q traefik); then
    docker network create traefik
fi

TRAEFIK_PORT=${TRAEFIK_PORT:-80}
TRAEFIK_DASHBOARD_URL=${TRAEFIK_DASHBOARD_URL:-"traefik.localhost"}
TRAEFIK_DASHBOARD_AUTH=${TRAEFIK_DASHBOARD_AUTH:-""}

LABELS="\
    -l traefik.enable=true \
    -l traefik.http.routers.dashboard.rule=Host(\`${TRAEFIK_DASHBOARD_URL}\`) \
    -l traefik.http.routers.dashboard.service=api@internal \
"

if [ -z ${TRAEFIK_DASHBOARD_AUTH+x} ]; then
    LABELS="${LABELS}\
        -l traefik.http.routers.dashboard.middlewares=dashboardauth \
        -l traefik.http.middlewares.dashboardauth.basicauth.users=${TRAEFIK_DASHBOARD_AUTH} \
    "
fi

docker run \
    --rm \
    -d \
    --name traefik \
    --privileged \
    -p ${TRAEFIK_PORT}:80 \
    --network traefik \
    -v /var/run/docker.sock:/var/run/docker.sock \
    ${LABELS} \
    traefik:latest \
    --providers.docker \
    --providers.docker.exposedbydefault=false \
    --providers.docker.network=traefik \
    --api.dashboard=true \
    --entrypoints.web.address=":${TRAEFIK_PORT}"